//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to {0}\\{1}.
    /// </summary>
    public static string IDS_DOMAINUSERFORMAT {
        get {
            return ResourceManager.GetString("IDS_DOMAINUSERFORMAT", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Usage:
    ///    TFBug [ID[ ID[...[ ID]]]] [-?]
    ///
    ///    ID  The numeric bug ID to query
    ///    -?  Display this message
    ///
    ///    If no arguments are specified, a default query (from configuration file) is used..
    /// </summary>
    public static string IDS_HELPMSG {
        get {
            return ResourceManager.GetString("IDS_HELPMSG", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Invalid bug ID \&quot;{0}\&quot;\n.
    /// </summary>
    public static string IDS_INVALIDBUGIDFORMAT {
        get {
            return ResourceManager.GetString("IDS_INVALIDBUGIDFORMAT", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to {0}: {1}.
    /// </summary>
    public static string IDS_NAMEVALUEFORMAT {
        get {
            return ResourceManager.GetString("IDS_NAMEVALUEFORMAT", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Updating TFS cache for well-known servers....
    /// </summary>
    public static string IDS_UPDATECACHEMSG {
        get {
            return ResourceManager.GetString("IDS_UPDATECACHEMSG", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to There is no working folder mapping for {0} and no suitable workspace could be found..
    /// </summary>
    public static string IDS_WARN_NOMAPPING {
        get {
            return ResourceManager.GetString("IDS_WARN_NOMAPPING", resourceCulture);
        }
    }
}
